### PR TITLE
Adding hooks to get into the admin view with custom panels

### PR DESCRIPTION
**Pull request by ekandreas**
Making it possible to add custom admin panels into the main page at Arlima.
Need to put some specific panels, eg create a Mailchimp campaign out of an Arlima list.

### CODE REVIEW

**Comment by EkAndreas** [comment]
Perhaps my hook-names wont fit to your standards, should I change them into something better, perhaps?

**Comment by EkAndreas** [comment]
Also I would like to add some controls to manage the selected list.
Perhaps add a hook in the "article-controls"?

**Comment by victorjonsson** [comment]
Yes, I was about to comment on that :) Something like arlima_admin_xyz. Add all the hooks you feel necessary.

**Comment by EkAndreas** [comment]
I have now changed the hook name to old name conventions. Sorry, but I'm following the ACF-idea of slash-separated hook names :-)

**Comment by victorjonsson** [comment]
No worries... Maybe you will like the configureable article (issue #67). When it's implemented you'll be able to change the article form completely.

**Comment by EkAndreas** [comment]
Thanks! Yes, looking forward to it!

**Pull request merged**
